#!/bin/bash

set -e
source "$(dirname "${BASH_SOURCE[0]}")/common"

url="$1"       # url name
id="$2"        # reply id

db_top="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../../db")"
accounts_top="$db_top/accounts"
article_dir="$db_top/articles/$url/_content"
reply_top="$db_top/articles/$url/comments"
reply_dir="$reply_top/$id/_content"

[[ "$url" == "" ]] && { echo 'no url specified'; exit 1; }
[[ ! -d "$article_dir" ]] && { echo 'url folder not found'; exit 1; }
[[ ! -d "$reply_dir" ]] && { echo 'reply folder not found'; exit 1; }

date=$(git config --file="$reply_dir/metadata" base.date)
registered=$(git config --file="$reply_dir/metadata" base.registered)
email=$(git config --file="$reply_dir/metadata" base.email)
[[ "$registered" == "true" ]] && user_from="$accounts_top/$email" || user_from="$reply_dir/metadata"
name=$(git config --file="$user_from" base.name)
site=$(git config --file="$user_from" base.site)
format=$(git config --file="$reply_dir/metadata" base.format)
body=$(cat "$reply_dir/body")

echo    "{\"id\":\"$id\","
echo    "\"date\":\"$date\","
echo    "\"registered\":\"$registered\","
echo    "\"name\":\"$name\","
echo    "\"email\":\"$(mask_email $email)\","
echo    "\"site\":$(json_escape "$site"),"
echo    "\"format\":\"$format\","
echo -n "\"body\":$(json_escape "$body")}"

exit 0
