#!/bin/bash

function json_escape(){
  echo -n "$1" | python2.7 -c 'import json,sys; print json.dumps(sys.stdin.read())'
}

set -e

url="$1"       # url name
show_body="$2" # true or not

db_top="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../../db")"
article_dir="$db_top/articles/$url/_content"

[[ "$url" == "" ]] && { echo '{"error":"no url specified"}'; exit 1; }
[[ ! -d "$article_dir" ]] && { echo '{"error":"url folder not found"}'; exit 1; }

title=$(git config --file="$article_dir/metadata" base.title)
date=$(git config --file="$article_dir/metadata" base.date)
attributes=$(git config --file="$article_dir/metadata" base.attributes)
count=$(cat "$article_dir/count")
format=$(git config --file="$article_dir/metadata" base.format)
summary=$(git config --file="$article_dir/metadata" base.summary)
body=$(cat "$article_dir/body")

echo    "{\"title\":$(json_escape "$title"),"
echo    "\"date\":\"$date\","
echo    "\"attributes\":\"$attributes\"," #TODO: filter sensitive data
echo    "\"count\":\"$count\","
echo    "\"format\":\"$format\","
echo -n "\"summary\":$(json_escape "$summary")"
if [[ "$show_body" != "true" ]]; then
  echo -n  "}"
else
  echo ","
  echo -n "\"body\":$(json_escape "$body")}"
fi

exit 0

