#!/bin/bash

config_file="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../../config.ini")"
smtp_host=$(git config --file="$config_file" smtp.host)
smtp_user=$(git config --file="$config_file" smtp.user)
smtp_password=$(git config --file="$config_file" smtp.password)
smtp_name=$(git config --file="$config_file" smtp.name)
smtp_subject=$(git config --file="$config_file" smtp.subject)
smtp_body=$(git config --file="$config_file" smtp.body)

smtp_to="$1" #format: "Duke Fong <duke@dukelec.com>"
password="$2" #the code send to user

[[ "$smtp_to" == "" || "$smtp_body" == "" || "$password" == "" ]] && exit 1

smtp_body=$(eval "echo \"$smtp_body\"")

"$(dirname "${BASH_SOURCE[0]}")/smtp-cli" --ipv4 --host="$smtp_host" --enable-auth \
  --user="$smtp_user" --pass="$smtp_password" --missing-modules-ok \
  --from="$smtp_name <$smtp_user>" --to="$smtp_to" \
  --subject="$smtp_subject" --body-plain="$smtp_body"

exit $?

#TODO: write to log file
