#!/bin/bash

set -e

captcha="$1" #format: data-string

[[ "$captcha" == "" ]] && exit 1
captcha=${captcha^^} #to uppercase

captcha_dir="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../.cache/captcha")"
config_file="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../../config.ini")"
cd "$captcha_dir"

captcha_timeout=$(git config --file="$config_file" captcha.timeout)

# delete file older than n min
find . -mmin +$captcha_timeout -type f -name "[!.]*" -delete

files=($(ls))

for i in "${!files[@]}"; do
  [[ "$captcha" == "${files[i]}" ]] && { rm -f "$captcha"; exit 0; }
done

exit 1

