#!/bin/bash

set -e

date="$1"
string="$2"

[[ "$date" == "" ]] && exit 1
[[ "$string" == "" ]] && exit 1

string=${string,,} #to lowercase

captcha_dir="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../.cache/captcha")"
config_file="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../../config.ini")"
cd "$captcha_dir"

captcha_timeout=$(git config --file="$config_file" captcha.timeout)

# delete file older than n min
find . -mmin +$captcha_timeout -type f -delete

files=($(ls))

for i in "${!files[@]}"; do
  [[ "$date-$string" == "${files[i]}" ]] && { rm -f "$date-$string"; exit 0; }
done

exit 1
