#!/usr/bin/env python3
#
# Software License Agreement (MIT License)
# Author: Duke Fong <d@d-l.io>

import cgi, sys, os, json
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from conf.gconf import gconf

print('Content-Type: application/json; charset=utf-8\n')

form = cgi.FieldStorage()
url = form.getvalue('url')

article_dir = '../articles/' + url

with open(article_dir + '/_metadata', 'r') as file:
    metadata = json.loads(file.read())

if 'summary' not in metadata.keys():
    with open(article_dir + '/summary.%s' % metadata['formats']['summary'], 'r') as file:
        metadata['summary'] = file.read()
try:
    with open(article_dir + '/_count', 'r') as file:
        metadata['count'] = int(file.read())
except:
    metadata['count'] = 0

with open(article_dir + '/_count', 'w') as file:
    file.write(str(metadata['count'] + 1))

with open(article_dir + '/body.%s' % metadata['formats']['body'], 'r') as file:
    metadata['body'] = file.read()

if '_comments' in os.listdir(article_dir):
    metadata['comments'] = []
    for n in os.listdir(article_dir + '/_comments'):
        if not n.isdigit():
            continue
        comment_dir = article_dir + '/_comments/%s' % n
        with open(comment_dir + '/_metadata', 'r') as file:
            comment = json.loads(file.read())
        del comment['email']
        comment = {'id': int(n), **comment} # put the id at the top
        with open(comment_dir + '/body.%s' % comment['format'], 'r') as file:
            comment['body'] = file.read()
        metadata['comments'].append(comment)
    
    metadata['comments'].sort(key=lambda x: x['id'], reverse=False)

print(json.dumps(metadata, indent=2, ensure_ascii=False, sort_keys=False))

