#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import cgi, sys, os, json
from collections import OrderedDict

print('Content-Type: application/json; charset=utf-8\n')

#form = cgi.FieldStorage()
#user = form.getvalue('user')
#password = form.getvalue('password')

articles = []

for url in os.listdir('../db/articles'):
    article_dir = '../db/articles/' + url
    with open(article_dir + '/_metadata', 'r') as file:
        metadata = json.loads(file.read(), object_pairs_hook=OrderedDict)
    metadata['url'] = url
    metadata.move_to_end('url', last=False)
    if 'summary' not in metadata.keys():
        with open(article_dir + '/summary.%s' % metadata['formats']['summary'], 'r') as file:
            metadata['summary'] = file.read()
    try:
        with open(article_dir + '/_count', 'r') as file:
            metadata['count'] = int(file.read())
    except:
        metadata['count'] = 0
    articles.append(metadata)

articles.sort(key=lambda x: x['date'], reverse=True)
print(json.dumps(articles, indent=2, ensure_ascii=False, sort_keys=False))

